language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      script:
        - go get github.com/golang/lint/golint
        - golint
        - go vet
    - stage: test
      script:
        - go test -v
    - stage: release
      script:
        - echo "release to GitHub"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true
